#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="login")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void InsertadminLogin(adminLogin instance);
  partial void UpdateadminLogin(adminLogin instance);
  partial void DeleteadminLogin(adminLogin instance);
  partial void InsertCourse(Course instance);
  partial void UpdateCourse(Course instance);
  partial void DeleteCourse(Course instance);
  partial void InsertD_C(D_C instance);
  partial void UpdateD_C(D_C instance);
  partial void DeleteD_C(D_C instance);
  partial void InsertDepartment(Department instance);
  partial void UpdateDepartment(Department instance);
  partial void DeleteDepartment(Department instance);
  partial void InsertSGrade(SGrade instance);
  partial void UpdateSGrade(SGrade instance);
  partial void DeleteSGrade(SGrade instance);
  partial void InsertStu_information(Stu_information instance);
  partial void UpdateStu_information(Stu_information instance);
  partial void DeleteStu_information(Stu_information instance);
  partial void InsertstudentLogin(studentLogin instance);
  partial void UpdatestudentLogin(studentLogin instance);
  partial void DeletestudentLogin(studentLogin instance);
  partial void InsertT_information(T_information instance);
  partial void UpdateT_information(T_information instance);
  partial void DeleteT_information(T_information instance);
  partial void InsertteacherLogin(teacherLogin instance);
  partial void UpdateteacherLogin(teacherLogin instance);
  partial void DeleteteacherLogin(teacherLogin instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["loginConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<adminLogin> adminLogin
	{
		get
		{
			return this.GetTable<adminLogin>();
		}
	}
	
	public System.Data.Linq.Table<Course> Course
	{
		get
		{
			return this.GetTable<Course>();
		}
	}
	
	public System.Data.Linq.Table<D_C> D_C
	{
		get
		{
			return this.GetTable<D_C>();
		}
	}
	
	public System.Data.Linq.Table<Department> Department
	{
		get
		{
			return this.GetTable<Department>();
		}
	}
	
	public System.Data.Linq.Table<SGrade> SGrade
	{
		get
		{
			return this.GetTable<SGrade>();
		}
	}
	
	public System.Data.Linq.Table<Stu_information> Stu_information
	{
		get
		{
			return this.GetTable<Stu_information>();
		}
	}
	
	public System.Data.Linq.Table<studentLogin> studentLogin
	{
		get
		{
			return this.GetTable<studentLogin>();
		}
	}
	
	public System.Data.Linq.Table<T_information> T_information
	{
		get
		{
			return this.GetTable<T_information>();
		}
	}
	
	public System.Data.Linq.Table<teacherLogin> teacherLogin
	{
		get
		{
			return this.GetTable<teacherLogin>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.adminLogin")]
public partial class adminLogin : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _userType;
	
	private string _userName;
	
	private string _userPwd;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnuserTypeChanging(string value);
    partial void OnuserTypeChanged();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnuserPwdChanging(string value);
    partial void OnuserPwdChanged();
    #endregion
	
	public adminLogin()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userType", DbType="NVarChar(50)")]
	public string userType
	{
		get
		{
			return this._userType;
		}
		set
		{
			if ((this._userType != value))
			{
				this.OnuserTypeChanging(value);
				this.SendPropertyChanging();
				this._userType = value;
				this.SendPropertyChanged("userType");
				this.OnuserTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="NVarChar(50)")]
	public string userName
	{
		get
		{
			return this._userName;
		}
		set
		{
			if ((this._userName != value))
			{
				this.OnuserNameChanging(value);
				this.SendPropertyChanging();
				this._userName = value;
				this.SendPropertyChanged("userName");
				this.OnuserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userPwd", DbType="NVarChar(50)")]
	public string userPwd
	{
		get
		{
			return this._userPwd;
		}
		set
		{
			if ((this._userPwd != value))
			{
				this.OnuserPwdChanging(value);
				this.SendPropertyChanging();
				this._userPwd = value;
				this.SendPropertyChanged("userPwd");
				this.OnuserPwdChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Course")]
public partial class Course : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _CourseID;
	
	private string _CourseName;
	
	private string _TeacherName;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnCourseIDChanging(string value);
    partial void OnCourseIDChanged();
    partial void OnCourseNameChanging(string value);
    partial void OnCourseNameChanged();
    partial void OnTeacherNameChanging(string value);
    partial void OnTeacherNameChanged();
    #endregion
	
	public Course()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseID", DbType="NVarChar(50)")]
	public string CourseID
	{
		get
		{
			return this._CourseID;
		}
		set
		{
			if ((this._CourseID != value))
			{
				this.OnCourseIDChanging(value);
				this.SendPropertyChanging();
				this._CourseID = value;
				this.SendPropertyChanged("CourseID");
				this.OnCourseIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseName", DbType="NVarChar(50)")]
	public string CourseName
	{
		get
		{
			return this._CourseName;
		}
		set
		{
			if ((this._CourseName != value))
			{
				this.OnCourseNameChanging(value);
				this.SendPropertyChanging();
				this._CourseName = value;
				this.SendPropertyChanged("CourseName");
				this.OnCourseNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeacherName", DbType="NVarChar(50)")]
	public string TeacherName
	{
		get
		{
			return this._TeacherName;
		}
		set
		{
			if ((this._TeacherName != value))
			{
				this.OnTeacherNameChanging(value);
				this.SendPropertyChanging();
				this._TeacherName = value;
				this.SendPropertyChanged("TeacherName");
				this.OnTeacherNameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[D-C]")]
public partial class D_C : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _DName;
	
	private string _AClass;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnDNameChanging(string value);
    partial void OnDNameChanged();
    partial void OnAClassChanging(string value);
    partial void OnAClassChanged();
    #endregion
	
	public D_C()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DName", DbType="NVarChar(50)")]
	public string DName
	{
		get
		{
			return this._DName;
		}
		set
		{
			if ((this._DName != value))
			{
				this.OnDNameChanging(value);
				this.SendPropertyChanging();
				this._DName = value;
				this.SendPropertyChanged("DName");
				this.OnDNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AClass", DbType="NVarChar(50)")]
	public string AClass
	{
		get
		{
			return this._AClass;
		}
		set
		{
			if ((this._AClass != value))
			{
				this.OnAClassChanging(value);
				this.SendPropertyChanging();
				this._AClass = value;
				this.SendPropertyChanged("AClass");
				this.OnAClassChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Department")]
public partial class Department : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _DepartmentName;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnDepartmentNameChanging(string value);
    partial void OnDepartmentNameChanged();
    #endregion
	
	public Department()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentName", DbType="NVarChar(50)")]
	public string DepartmentName
	{
		get
		{
			return this._DepartmentName;
		}
		set
		{
			if ((this._DepartmentName != value))
			{
				this.OnDepartmentNameChanging(value);
				this.SendPropertyChanging();
				this._DepartmentName = value;
				this.SendPropertyChanged("DepartmentName");
				this.OnDepartmentNameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SGrade")]
public partial class SGrade : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _userNum;
	
	private string @__Name;
	
	private string @__class;
	
	private string _term;
	
	private string _courseName;
	
	private string _RegularGrade;
	
	private string _MidtermGrade;
	
	private string _FinalGrade;
	
	private string _WhetherQualified;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnuserNumChanging(string value);
    partial void OnuserNumChanged();
    partial void On_NameChanging(string value);
    partial void On_NameChanged();
    partial void On_classChanging(string value);
    partial void On_classChanged();
    partial void OntermChanging(string value);
    partial void OntermChanged();
    partial void OncourseNameChanging(string value);
    partial void OncourseNameChanged();
    partial void OnRegularGradeChanging(string value);
    partial void OnRegularGradeChanged();
    partial void OnMidtermGradeChanging(string value);
    partial void OnMidtermGradeChanged();
    partial void OnFinalGradeChanging(string value);
    partial void OnFinalGradeChanged();
    partial void OnWhetherQualifiedChanging(string value);
    partial void OnWhetherQualifiedChanged();
    #endregion
	
	public SGrade()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userNum", DbType="NVarChar(50)")]
	public string userNum
	{
		get
		{
			return this._userNum;
		}
		set
		{
			if ((this._userNum != value))
			{
				this.OnuserNumChanging(value);
				this.SendPropertyChanging();
				this._userNum = value;
				this.SendPropertyChanged("userNum");
				this.OnuserNumChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_Name]", Storage="__Name", DbType="NVarChar(50)")]
	public string _Name
	{
		get
		{
			return this.@__Name;
		}
		set
		{
			if ((this.@__Name != value))
			{
				this.On_NameChanging(value);
				this.SendPropertyChanging();
				this.@__Name = value;
				this.SendPropertyChanged("_Name");
				this.On_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_class]", Storage="__class", DbType="NVarChar(50)")]
	public string _class
	{
		get
		{
			return this.@__class;
		}
		set
		{
			if ((this.@__class != value))
			{
				this.On_classChanging(value);
				this.SendPropertyChanging();
				this.@__class = value;
				this.SendPropertyChanged("_class");
				this.On_classChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_term", DbType="NVarChar(50)")]
	public string term
	{
		get
		{
			return this._term;
		}
		set
		{
			if ((this._term != value))
			{
				this.OntermChanging(value);
				this.SendPropertyChanging();
				this._term = value;
				this.SendPropertyChanged("term");
				this.OntermChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_courseName", DbType="NVarChar(50)")]
	public string courseName
	{
		get
		{
			return this._courseName;
		}
		set
		{
			if ((this._courseName != value))
			{
				this.OncourseNameChanging(value);
				this.SendPropertyChanging();
				this._courseName = value;
				this.SendPropertyChanged("courseName");
				this.OncourseNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegularGrade", DbType="NVarChar(50)")]
	public string RegularGrade
	{
		get
		{
			return this._RegularGrade;
		}
		set
		{
			if ((this._RegularGrade != value))
			{
				this.OnRegularGradeChanging(value);
				this.SendPropertyChanging();
				this._RegularGrade = value;
				this.SendPropertyChanged("RegularGrade");
				this.OnRegularGradeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MidtermGrade", DbType="NVarChar(50)")]
	public string MidtermGrade
	{
		get
		{
			return this._MidtermGrade;
		}
		set
		{
			if ((this._MidtermGrade != value))
			{
				this.OnMidtermGradeChanging(value);
				this.SendPropertyChanging();
				this._MidtermGrade = value;
				this.SendPropertyChanged("MidtermGrade");
				this.OnMidtermGradeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinalGrade", DbType="NVarChar(50)")]
	public string FinalGrade
	{
		get
		{
			return this._FinalGrade;
		}
		set
		{
			if ((this._FinalGrade != value))
			{
				this.OnFinalGradeChanging(value);
				this.SendPropertyChanging();
				this._FinalGrade = value;
				this.SendPropertyChanged("FinalGrade");
				this.OnFinalGradeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WhetherQualified", DbType="NVarChar(50)")]
	public string WhetherQualified
	{
		get
		{
			return this._WhetherQualified;
		}
		set
		{
			if ((this._WhetherQualified != value))
			{
				this.OnWhetherQualifiedChanging(value);
				this.SendPropertyChanging();
				this._WhetherQualified = value;
				this.SendPropertyChanged("WhetherQualified");
				this.OnWhetherQualifiedChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Stu_information")]
public partial class Stu_information : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _stuNum;
	
	private string _stuName;
	
	private string _stuSex;
	
	private string _birthday;
	
	private string _nationType;
	
	private string _IdentityID;
	
	private string _Province;
	
	private string _City;
	
	private string _Area;
	
	private string _Address;
	
	private string _PoliticalStatus;
	
	private string @__class;
	
	private string _department;
	
	private string _EnrollmentYear;
	
	private string _studyYear;
	
	private string _Tel;
	
	private string _E_mail;
	
	private string _picture;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnstuNumChanging(string value);
    partial void OnstuNumChanged();
    partial void OnstuNameChanging(string value);
    partial void OnstuNameChanged();
    partial void OnstuSexChanging(string value);
    partial void OnstuSexChanged();
    partial void OnbirthdayChanging(string value);
    partial void OnbirthdayChanged();
    partial void OnnationTypeChanging(string value);
    partial void OnnationTypeChanged();
    partial void OnIdentityIDChanging(string value);
    partial void OnIdentityIDChanged();
    partial void OnProvinceChanging(string value);
    partial void OnProvinceChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnAreaChanging(string value);
    partial void OnAreaChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnPoliticalStatusChanging(string value);
    partial void OnPoliticalStatusChanged();
    partial void On_classChanging(string value);
    partial void On_classChanged();
    partial void OndepartmentChanging(string value);
    partial void OndepartmentChanged();
    partial void OnEnrollmentYearChanging(string value);
    partial void OnEnrollmentYearChanged();
    partial void OnstudyYearChanging(string value);
    partial void OnstudyYearChanged();
    partial void OnTelChanging(string value);
    partial void OnTelChanged();
    partial void OnE_mailChanging(string value);
    partial void OnE_mailChanged();
    partial void OnpictureChanging(string value);
    partial void OnpictureChanged();
    #endregion
	
	public Stu_information()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stuNum", DbType="NVarChar(50)")]
	public string stuNum
	{
		get
		{
			return this._stuNum;
		}
		set
		{
			if ((this._stuNum != value))
			{
				this.OnstuNumChanging(value);
				this.SendPropertyChanging();
				this._stuNum = value;
				this.SendPropertyChanged("stuNum");
				this.OnstuNumChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stuName", DbType="NVarChar(50)")]
	public string stuName
	{
		get
		{
			return this._stuName;
		}
		set
		{
			if ((this._stuName != value))
			{
				this.OnstuNameChanging(value);
				this.SendPropertyChanging();
				this._stuName = value;
				this.SendPropertyChanged("stuName");
				this.OnstuNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stuSex", DbType="NVarChar(50)")]
	public string stuSex
	{
		get
		{
			return this._stuSex;
		}
		set
		{
			if ((this._stuSex != value))
			{
				this.OnstuSexChanging(value);
				this.SendPropertyChanging();
				this._stuSex = value;
				this.SendPropertyChanged("stuSex");
				this.OnstuSexChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="NVarChar(50)")]
	public string birthday
	{
		get
		{
			return this._birthday;
		}
		set
		{
			if ((this._birthday != value))
			{
				this.OnbirthdayChanging(value);
				this.SendPropertyChanging();
				this._birthday = value;
				this.SendPropertyChanged("birthday");
				this.OnbirthdayChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nationType", DbType="NVarChar(50)")]
	public string nationType
	{
		get
		{
			return this._nationType;
		}
		set
		{
			if ((this._nationType != value))
			{
				this.OnnationTypeChanging(value);
				this.SendPropertyChanging();
				this._nationType = value;
				this.SendPropertyChanged("nationType");
				this.OnnationTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdentityID", DbType="NVarChar(50)")]
	public string IdentityID
	{
		get
		{
			return this._IdentityID;
		}
		set
		{
			if ((this._IdentityID != value))
			{
				this.OnIdentityIDChanging(value);
				this.SendPropertyChanging();
				this._IdentityID = value;
				this.SendPropertyChanged("IdentityID");
				this.OnIdentityIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Province", DbType="NVarChar(50)")]
	public string Province
	{
		get
		{
			return this._Province;
		}
		set
		{
			if ((this._Province != value))
			{
				this.OnProvinceChanging(value);
				this.SendPropertyChanging();
				this._Province = value;
				this.SendPropertyChanged("Province");
				this.OnProvinceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(50)")]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this.OnCityChanging(value);
				this.SendPropertyChanging();
				this._City = value;
				this.SendPropertyChanged("City");
				this.OnCityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="NVarChar(50)")]
	public string Area
	{
		get
		{
			return this._Area;
		}
		set
		{
			if ((this._Area != value))
			{
				this.OnAreaChanging(value);
				this.SendPropertyChanging();
				this._Area = value;
				this.SendPropertyChanged("Area");
				this.OnAreaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(50)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PoliticalStatus", DbType="NVarChar(50)")]
	public string PoliticalStatus
	{
		get
		{
			return this._PoliticalStatus;
		}
		set
		{
			if ((this._PoliticalStatus != value))
			{
				this.OnPoliticalStatusChanging(value);
				this.SendPropertyChanging();
				this._PoliticalStatus = value;
				this.SendPropertyChanged("PoliticalStatus");
				this.OnPoliticalStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_class]", Storage="__class", DbType="NVarChar(50)")]
	public string _class
	{
		get
		{
			return this.@__class;
		}
		set
		{
			if ((this.@__class != value))
			{
				this.On_classChanging(value);
				this.SendPropertyChanging();
				this.@__class = value;
				this.SendPropertyChanged("_class");
				this.On_classChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department", DbType="NVarChar(50)")]
	public string department
	{
		get
		{
			return this._department;
		}
		set
		{
			if ((this._department != value))
			{
				this.OndepartmentChanging(value);
				this.SendPropertyChanging();
				this._department = value;
				this.SendPropertyChanged("department");
				this.OndepartmentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnrollmentYear", DbType="NVarChar(50)")]
	public string EnrollmentYear
	{
		get
		{
			return this._EnrollmentYear;
		}
		set
		{
			if ((this._EnrollmentYear != value))
			{
				this.OnEnrollmentYearChanging(value);
				this.SendPropertyChanging();
				this._EnrollmentYear = value;
				this.SendPropertyChanged("EnrollmentYear");
				this.OnEnrollmentYearChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studyYear", DbType="NVarChar(50)")]
	public string studyYear
	{
		get
		{
			return this._studyYear;
		}
		set
		{
			if ((this._studyYear != value))
			{
				this.OnstudyYearChanging(value);
				this.SendPropertyChanging();
				this._studyYear = value;
				this.SendPropertyChanged("studyYear");
				this.OnstudyYearChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(50)")]
	public string Tel
	{
		get
		{
			return this._Tel;
		}
		set
		{
			if ((this._Tel != value))
			{
				this.OnTelChanging(value);
				this.SendPropertyChanging();
				this._Tel = value;
				this.SendPropertyChanged("Tel");
				this.OnTelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[E-mail]", Storage="_E_mail", DbType="NVarChar(50)")]
	public string E_mail
	{
		get
		{
			return this._E_mail;
		}
		set
		{
			if ((this._E_mail != value))
			{
				this.OnE_mailChanging(value);
				this.SendPropertyChanging();
				this._E_mail = value;
				this.SendPropertyChanged("E_mail");
				this.OnE_mailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_picture", DbType="NVarChar(50)")]
	public string picture
	{
		get
		{
			return this._picture;
		}
		set
		{
			if ((this._picture != value))
			{
				this.OnpictureChanging(value);
				this.SendPropertyChanging();
				this._picture = value;
				this.SendPropertyChanged("picture");
				this.OnpictureChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.studentLogin")]
public partial class studentLogin : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _userType;
	
	private string _userName;
	
	private string _userPwd;
	
	private string @__Name;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnuserTypeChanging(string value);
    partial void OnuserTypeChanged();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnuserPwdChanging(string value);
    partial void OnuserPwdChanged();
    partial void On_NameChanging(string value);
    partial void On_NameChanged();
    #endregion
	
	public studentLogin()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userType", DbType="NVarChar(20)")]
	public string userType
	{
		get
		{
			return this._userType;
		}
		set
		{
			if ((this._userType != value))
			{
				this.OnuserTypeChanging(value);
				this.SendPropertyChanging();
				this._userType = value;
				this.SendPropertyChanged("userType");
				this.OnuserTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="NVarChar(20)")]
	public string userName
	{
		get
		{
			return this._userName;
		}
		set
		{
			if ((this._userName != value))
			{
				this.OnuserNameChanging(value);
				this.SendPropertyChanging();
				this._userName = value;
				this.SendPropertyChanged("userName");
				this.OnuserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userPwd", DbType="NVarChar(20)")]
	public string userPwd
	{
		get
		{
			return this._userPwd;
		}
		set
		{
			if ((this._userPwd != value))
			{
				this.OnuserPwdChanging(value);
				this.SendPropertyChanging();
				this._userPwd = value;
				this.SendPropertyChanged("userPwd");
				this.OnuserPwdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_Name]", Storage="__Name", DbType="NVarChar(20)")]
	public string _Name
	{
		get
		{
			return this.@__Name;
		}
		set
		{
			if ((this.@__Name != value))
			{
				this.On_NameChanging(value);
				this.SendPropertyChanging();
				this.@__Name = value;
				this.SendPropertyChanged("_Name");
				this.On_NameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_information")]
public partial class T_information : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _TNum;
	
	private string _TName;
	
	private string _TSex;
	
	private string _birthday;
	
	private string _nationType;
	
	private string _IdentityID;
	
	private string _Province;
	
	private string _City;
	
	private string _Area;
	
	private string _Address;
	
	private string _PoliticalStatus;
	
	private string @__class;
	
	private string _department;
	
	private string _EnrollmentYear;
	
	private string _workYear;
	
	private string _Tel;
	
	private string _E_mail;
	
	private string _picture;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnTNumChanging(string value);
    partial void OnTNumChanged();
    partial void OnTNameChanging(string value);
    partial void OnTNameChanged();
    partial void OnTSexChanging(string value);
    partial void OnTSexChanged();
    partial void OnbirthdayChanging(string value);
    partial void OnbirthdayChanged();
    partial void OnnationTypeChanging(string value);
    partial void OnnationTypeChanged();
    partial void OnIdentityIDChanging(string value);
    partial void OnIdentityIDChanged();
    partial void OnProvinceChanging(string value);
    partial void OnProvinceChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnAreaChanging(string value);
    partial void OnAreaChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnPoliticalStatusChanging(string value);
    partial void OnPoliticalStatusChanged();
    partial void On_classChanging(string value);
    partial void On_classChanged();
    partial void OndepartmentChanging(string value);
    partial void OndepartmentChanged();
    partial void OnEnrollmentYearChanging(string value);
    partial void OnEnrollmentYearChanged();
    partial void OnworkYearChanging(string value);
    partial void OnworkYearChanged();
    partial void OnTelChanging(string value);
    partial void OnTelChanged();
    partial void OnE_mailChanging(string value);
    partial void OnE_mailChanged();
    partial void OnpictureChanging(string value);
    partial void OnpictureChanged();
    #endregion
	
	public T_information()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TNum", DbType="NVarChar(50)")]
	public string TNum
	{
		get
		{
			return this._TNum;
		}
		set
		{
			if ((this._TNum != value))
			{
				this.OnTNumChanging(value);
				this.SendPropertyChanging();
				this._TNum = value;
				this.SendPropertyChanged("TNum");
				this.OnTNumChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TName", DbType="NVarChar(50)")]
	public string TName
	{
		get
		{
			return this._TName;
		}
		set
		{
			if ((this._TName != value))
			{
				this.OnTNameChanging(value);
				this.SendPropertyChanging();
				this._TName = value;
				this.SendPropertyChanged("TName");
				this.OnTNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TSex", DbType="NVarChar(50)")]
	public string TSex
	{
		get
		{
			return this._TSex;
		}
		set
		{
			if ((this._TSex != value))
			{
				this.OnTSexChanging(value);
				this.SendPropertyChanging();
				this._TSex = value;
				this.SendPropertyChanged("TSex");
				this.OnTSexChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="NVarChar(50)")]
	public string birthday
	{
		get
		{
			return this._birthday;
		}
		set
		{
			if ((this._birthday != value))
			{
				this.OnbirthdayChanging(value);
				this.SendPropertyChanging();
				this._birthday = value;
				this.SendPropertyChanged("birthday");
				this.OnbirthdayChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nationType", DbType="NVarChar(50)")]
	public string nationType
	{
		get
		{
			return this._nationType;
		}
		set
		{
			if ((this._nationType != value))
			{
				this.OnnationTypeChanging(value);
				this.SendPropertyChanging();
				this._nationType = value;
				this.SendPropertyChanged("nationType");
				this.OnnationTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdentityID", DbType="NVarChar(50)")]
	public string IdentityID
	{
		get
		{
			return this._IdentityID;
		}
		set
		{
			if ((this._IdentityID != value))
			{
				this.OnIdentityIDChanging(value);
				this.SendPropertyChanging();
				this._IdentityID = value;
				this.SendPropertyChanged("IdentityID");
				this.OnIdentityIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Province", DbType="NVarChar(50)")]
	public string Province
	{
		get
		{
			return this._Province;
		}
		set
		{
			if ((this._Province != value))
			{
				this.OnProvinceChanging(value);
				this.SendPropertyChanging();
				this._Province = value;
				this.SendPropertyChanged("Province");
				this.OnProvinceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(50)")]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this.OnCityChanging(value);
				this.SendPropertyChanging();
				this._City = value;
				this.SendPropertyChanged("City");
				this.OnCityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="NVarChar(50)")]
	public string Area
	{
		get
		{
			return this._Area;
		}
		set
		{
			if ((this._Area != value))
			{
				this.OnAreaChanging(value);
				this.SendPropertyChanging();
				this._Area = value;
				this.SendPropertyChanged("Area");
				this.OnAreaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(50)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PoliticalStatus", DbType="NVarChar(50)")]
	public string PoliticalStatus
	{
		get
		{
			return this._PoliticalStatus;
		}
		set
		{
			if ((this._PoliticalStatus != value))
			{
				this.OnPoliticalStatusChanging(value);
				this.SendPropertyChanging();
				this._PoliticalStatus = value;
				this.SendPropertyChanged("PoliticalStatus");
				this.OnPoliticalStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_class]", Storage="__class", DbType="NVarChar(255)")]
	public string _class
	{
		get
		{
			return this.@__class;
		}
		set
		{
			if ((this.@__class != value))
			{
				this.On_classChanging(value);
				this.SendPropertyChanging();
				this.@__class = value;
				this.SendPropertyChanged("_class");
				this.On_classChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department", DbType="NVarChar(50)")]
	public string department
	{
		get
		{
			return this._department;
		}
		set
		{
			if ((this._department != value))
			{
				this.OndepartmentChanging(value);
				this.SendPropertyChanging();
				this._department = value;
				this.SendPropertyChanged("department");
				this.OndepartmentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnrollmentYear", DbType="NVarChar(50)")]
	public string EnrollmentYear
	{
		get
		{
			return this._EnrollmentYear;
		}
		set
		{
			if ((this._EnrollmentYear != value))
			{
				this.OnEnrollmentYearChanging(value);
				this.SendPropertyChanging();
				this._EnrollmentYear = value;
				this.SendPropertyChanged("EnrollmentYear");
				this.OnEnrollmentYearChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workYear", DbType="NVarChar(50)")]
	public string workYear
	{
		get
		{
			return this._workYear;
		}
		set
		{
			if ((this._workYear != value))
			{
				this.OnworkYearChanging(value);
				this.SendPropertyChanging();
				this._workYear = value;
				this.SendPropertyChanged("workYear");
				this.OnworkYearChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(50)")]
	public string Tel
	{
		get
		{
			return this._Tel;
		}
		set
		{
			if ((this._Tel != value))
			{
				this.OnTelChanging(value);
				this.SendPropertyChanging();
				this._Tel = value;
				this.SendPropertyChanged("Tel");
				this.OnTelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[E-mail]", Storage="_E_mail", DbType="NVarChar(50)")]
	public string E_mail
	{
		get
		{
			return this._E_mail;
		}
		set
		{
			if ((this._E_mail != value))
			{
				this.OnE_mailChanging(value);
				this.SendPropertyChanging();
				this._E_mail = value;
				this.SendPropertyChanged("E_mail");
				this.OnE_mailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_picture", DbType="NVarChar(50)")]
	public string picture
	{
		get
		{
			return this._picture;
		}
		set
		{
			if ((this._picture != value))
			{
				this.OnpictureChanging(value);
				this.SendPropertyChanging();
				this._picture = value;
				this.SendPropertyChanged("picture");
				this.OnpictureChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.teacherLogin")]
public partial class teacherLogin : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _userType;
	
	private string _userName;
	
	private string _userPwd;
	
	private string @__Name;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnuserTypeChanging(string value);
    partial void OnuserTypeChanged();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnuserPwdChanging(string value);
    partial void OnuserPwdChanged();
    partial void On_NameChanging(string value);
    partial void On_NameChanged();
    #endregion
	
	public teacherLogin()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userType", DbType="NVarChar(50)")]
	public string userType
	{
		get
		{
			return this._userType;
		}
		set
		{
			if ((this._userType != value))
			{
				this.OnuserTypeChanging(value);
				this.SendPropertyChanging();
				this._userType = value;
				this.SendPropertyChanged("userType");
				this.OnuserTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="NVarChar(50)")]
	public string userName
	{
		get
		{
			return this._userName;
		}
		set
		{
			if ((this._userName != value))
			{
				this.OnuserNameChanging(value);
				this.SendPropertyChanging();
				this._userName = value;
				this.SendPropertyChanged("userName");
				this.OnuserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userPwd", DbType="NVarChar(50)")]
	public string userPwd
	{
		get
		{
			return this._userPwd;
		}
		set
		{
			if ((this._userPwd != value))
			{
				this.OnuserPwdChanging(value);
				this.SendPropertyChanging();
				this._userPwd = value;
				this.SendPropertyChanged("userPwd");
				this.OnuserPwdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_Name]", Storage="__Name", DbType="NVarChar(50)")]
	public string _Name
	{
		get
		{
			return this.@__Name;
		}
		set
		{
			if ((this.@__Name != value))
			{
				this.On_NameChanging(value);
				this.SendPropertyChanging();
				this.@__Name = value;
				this.SendPropertyChanged("_Name");
				this.On_NameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
